### ISSUE TITLE
Atmosphere crashes when perfectly timed B-Press

### ISSUE THREAD

**Issue by KirbyKing186** [meganukebmp/Switch_90DNS_tester#10] opened 2023-07-14 03:05 UTC
NOTE: This issue only happens when in docked mode.

In handheld, when you press B exactly when the last result of the test comes back, either in applet mode or regular, nothing happens and you’re brought back the the HB-Menu.

Oddly, when in docked mode, the results are wildly different. 

In regular mode, pressing B exactly crashes whatever game was overridden, returning you to the home screen.
In applet mode (via album), pressing B exactly crashes atmosphere itself, giving with the provided error.
![IMG_8617](https://github.com/meganukebmp/Switch_90DNS_tester/assets/125282065/812a0c3e-6dfd-45ac-a845-643f0778011c)

**Comment by meganukebmp** [comment] 2023-08-24 10:34
Sorry for late reply. I have confirmed and reproduced this issue. It seems to be some sort of race condition originating in libnx sockets. My guess is that the socket is being closed while stuff is still running, which **shouldn't** happen. I recompiled with the latest libnx and it seems to have resolved the issue. I have attached a test build. Can you please see if this resolved the issue for you?

[Switch_90DNS_tester.zip](https://github.com/meganukebmp/Switch_90DNS_tester/files/12428427/Switch_90DNS_tester.zip)

**Comment by KirbyKing186** [comment] 2023-08-25 01:39
I have tested the new .nro in handheld, docked, handheld applet, docked applet, for multiple times. I believe it’s safe to say the bug has been fixed!

**Comment by Cocolin67** [comment] 2024-06-05 06:52
Any news on this issue ?

**Comment by meganukebmp** [comment] 2024-06-16 16:52
> Any news on this issue ?

This issue was due to a Libnx bug and is not due to this program's code. There's an above attached build that solves this issue. There are no code changes needed to solve this so I'll just close this issue.

**Closed as completed by meganukebmp** 2024-06-16 16:52 UTC
Labels: bug
